key_words = [
    'wasser', 'milch', 'zucker', 'weizenmehl', 'wass', 'schweinefleisch', 'kartoffeln', 'mineralwasser', 
    'joghurt', 'hartweizengriess', 'sonnenblumenöl', 'tomaten', 'rindfleisch', 'weizen', 
    'rahm', 'pouletfleisch', 'oliven', 'mais', 'kakaomasse', 'hagebuttenkarkadeblüten',
    'dinkelmehl', 'schwarztee', 'milchschokolade', 'salz', 'reis', 'vollmilchjoghurt', 'erdnüsse', 
    'lachs', 'rahmjoghurt', 'käse', 'haferflocken', 'apfelsaft', 'frischkäse', 'endiviensalat',
    'vollmilchschokolade', 'endivien', 'salmo', 'salar', 'magerquark', 'hartweizendunst', 
    'kichererbsen', 'glukosesirup', 'quark', 'karotten', 'sultaninen', 'gurken', 'fett', 'atlantischer', 
    'oncorhynchus', 'mandeln', 'spinat', 'hafer', 'teigwaren', 'poulet', 'wirz', 'gurke',
    'ananas', 'viertelfett', 'quorn', 'weisskohl', 'china', 'getreide', 'fruchtsäfte', 
    'fruchtmark', 'gemüse', 'weissmehl', 'kalbfleisch', 'cranberries', 'passionfrucht',
    'halbrahm', 'maisgriess', 'rapsöl', 'butter', 'trutenfleisch', 'pilzprodukt', 'cashewnüsse', 
    'aprikosen', 'kartoffelpulver', 'molke', 'magerjoghurt', 'äpfel', 'dorsch', 
    'getrocknet', 'salatsauce', 'bohnen', 'rohrohrzucker', 'mu', 'err', 'bundzwiebeln',
    'jogurt', 'regenbogenforelle', 'mykiss', 'sojabohnen', 'water', 'tomatenmark', 'crevetten', 
    'champignons', 'eier', 'kopfsalat', 'kaffeerahm', 'rot', 'maltodextrin', 'weizenvollkornmehl', 
    'apfel', 'aas', 'früchte', 'tomatenkonzentrat', 'linsen', 'kabeljau', 'grüntee', 'weizenbrot', 
    'gluten', 'citronensäure', 'getreidemehle', 'weinessig', 'spargelspitzen',
    'roggenvollkornmehl', 'litopenaeus', 'vannamei', 'essig', 'weisse', 'spargeln', 
    'halbhartkäse', 'gerstenmalzextrakt', 'eierteigwaren', 'mango', 'dinkel', 'fruchtsaftkonzentraten', 
    'bonito', 'katsuwonus', 'pelamis', 'weisser', 'thon', 'cornichons', 'tomatensaft', 'halbfett', 
    'mozzarella', 'rehydratisiert', 'alaska', 'seelachs', 'alaskapollack', 'forellenfilet', 'helles',
    'baumwollsamenöl', 'hafervollkornflocken', 'vollkornmehl', 'traubensaft', 'kartoffelstärke', 
    'säuerungsmittel', 'angereichert', 'hartkäse', 'maismehl', 'milchfett', 'calcium', 'gruyère', 
    'aquella', 'halbweissmehl', 'urdinkelmehl', 'dinkelvollkornmehl', 'pflanzliche', 'natriumchlorid',
    'getrocknete', 'sauerrahm', 'silberzwiebeln', 'reismehl', 'fleischerzeugnis', 'sorte', 
    'fruktoseglukosesirup', 'schokolade', 'vollkornhaferflocken', 'vollkornweizen', 'fünfkornmehl', 
    'sonnenblumenkerne', 'orangensaft', 'konzentraten', 'sojaproteine', 'sojaprotein', 'texturiertes', 
    'sojakonzentrat', 'konzentriert', 'himbeeren', 'toastbrot', 'eizubereitung', 'sellerie', 
    'rauchlachs', 'erbsen', 'roggenmehl', 'isomalt', 'himbeerjohannisbeerzubereitung',
    'gelatine', 'rote', 'nudelnest', 'tomatenfruchtfleisch', 'gezuckerte', 'kondensmilch', 
    'milchgetränk', 'gezuckert', 'calciumcaseinat', 'rohrzucker', 'wildlachs', 'weizenweissmehl', 
    'milchprotein', 'nudeln', 'kokosmilch', 'tomatenketchup', 'öle', 'palm', 'haselnüsse', 
    'mager', 'sauermilch', 'trinkwasser', 'maiskölbchen', 'crisprice', 'cervelat', 'orangen', 'püree', 
    'romanasalat', 'pfirsiche', 'birnen', 'eierschwämme', 'thunnus', 'alalunga', 'gemüsemischung', 
    'frühlingsrollen', 'vollfett', 'zitronensaft', 'trauben', 'pouletbrustfleisch', 'königslachs', 
    'tshawytscha', 'kartoffelzubereitung', 'gadus', 'eisbergsalat', 'eichblatt', 'schnittlauch', 'krevetten',
    'kokosnussextrakt', 'vollei', 'laugengipfel', 'soja', 'sorbit', 'pistazien', 
    'roggenvollkornschrot', 'kürbiskerne', 'kokosraspel', 'fruchtsaft', 
    'natives', 'olivenöl', 'kichererbsenmehl', 'blütenhonig', 'saurer', 'joghurtüberzug', 'sulfit',
    'cashewkerne', 'paprika', 'backmittel', 'diphosphate', 'brombeeren', 'ruchmehl', 'sockeye', 
    'maisstärke', 'zonen', 'zuckerrüben', 'hefe', 'kaese', 
    'weiss', 'halbweiss', 'pazifischer', 'coholachs', 'datteln', 
    'geschält', 'beutel', 'backmischung', 'erdnuss', 'erdbeeren', 'speck', 'tofu', 'carbonated', 'kürbis',
    'büffelmilch', 'endivie', 'greyerzer', 'saphir', 'gojibeeren', 'chilisauce', 'sweetsour', 'kakaobutter',
    'ki', 'rehydrierte', 'borlottibohnen', 'hartweizengrieß', 'regenbogenforellenfilets',
    'ei', 'flusskrebse', 'procambarus', 'clarkii', 'schlangenbohnen', 'pouletbrust',
    'weizenflocken', 'edamer', 'dreiviertelfett', 'malzhaltiges', 'getränkepulver', 'ovomaltine', 
    'fruchtmarkmischung', 'senf', 'tatsoi', 'omaten', 'joghurtgeschmack', 'dinkelflakes', 
    'parboiled', 'trockenpflaumen', 'rahmpulver', 'pfirsichsaft', 'sarasay', 'cocktail', 'béchamel', 
    'sauce', 'williamsbirnen', 'weissrussland', 'artischockenherzen', 'maiskörner', 'kapern', 'langkornreis',
    'pfefferschoten', 'dorschfilets', 'fischfleisch', 'halbhartkäsen', 'kammmuschelfleisch', 'pouletschnitzel',
    'weichtiere', 'gewichtsanteilen', 'riesenkalmar', 'seehecht', 'morhua', 'thonzubereitung', 
    'dressing', 'balsamico', 'sandwichbrot', 'pouletfleischerzeugnis', 'spezialbrot', 'thonerzeugnis',
    'ravioli', 'gekraust', 'knoblauch', 'randen', 'broccoli', 'johannisbeere', 'reisweizenflakes', 'feigen',
    'kartoffelflocken', 'zubereitung', 'metapenaeus', 'monoceros', 'mayonnaise', 'proteine', 'pangasiusfilets',
    'ananasstücke', 'aasstücke', 'kräutern', 'melisse', 'weizenproteine', 'rehydriert', 'chia',
    'eierspätzle', 'eierspätzli', 'sardellenfilets', 'engraulis', 'encrasicolus', 'sardellen', 'kokosraspeln',
    'vollkornflocken', 'hell', 'chiasamen', 'salvia', 'hispanica', 'mandel', 'seitan', 'aprikosenzubereitung',
    'zitronensaftkonzentrat', 'schmelzkäsezubereitung', 'pweizenmehl', 'ips', 'vollkorn', 'apfelsaftkonzentrat',
    'xylit', 'streichschmelzkäsezubereitung', 'rehydriertes', 'magermilchpulver', 'fruchtmus', 'red', 'bierrettich',
    'chard', 'stärkezucker', 'pflanzenproteine', 'hydrolysiert', 'clementinen', 'limetten', 'melone', 'kaki',
    'kartoffelgranulat', 'mangoschnitze', 'beluga', 'kokosnuss', 'saure', 'buttermilch', 'eiweiss', 'drink', 
    'ciporosa', 'mars', 'natrium', 'gewürze', 'fettarmer', 'zartbitterschokolade', 'milcheiweiß', 'chicorée',
    'molkeneiweißisolat', 'geröstete', 'süssholzwurzel', 'schweine', 'mineralsalze', 'rübenzucker', 'pfefferminzblätter',
    'roggenschrot', 'honig', 'alkoholessig', 'pfeffer', 'schwarz', 'weichkäse', 'butterfraktionen', 'raclettekäse', 
    'vollfetthalbhartkäse', 'gesamtmineralisation', 'rohe', 'zuckrt', 'kaltgepresstes', 'rooibos', 'rahmangereichertes', 
    'entrahmes', 'cornflakes', 'appenzeller', 'hirseflocken', 'crêpe', 'lactose', 'magermilchjoghurt', 'kiwis',
    'kokosnussfruchtfleisch', 'hühnerfleisch', 'kirschen', 'ascorbinsäure', 'vollkornreis', 
    'schokoladencreme', 'macrocephalus', 'edamame', 'soisson', 'rotkohl', 'vollkornhartweizengriess', 'zwetschgen', 
    'gepufft', 'weiß', 'walnüsse', 'inulin', 'doppelrahmfrischkäse', 'himbeerzubereitung', 'fleischkäse', 'pinklachs', 
    'gorbuscha', 'ketalachs', 'keta', 'biofeta', 'feta' 'tête', 'moine', 'emmentaler', 'wurst', 'kichererbsenzubereitung', 
    'bioeier', 'avocado', 'apfelessig', 'hibiskus', 'apfelbestandteile', 'hagebutten', 'blanchiert', 'mineral', 
    'hühnereiweiss', 'grillsteak', 'tomatenwürfel', 'weizenmehle', 'erfrischungsgetränk', 'marronipüree', 'marroni', 'carotin', 
    'zwiebeln', 'crème', 'fraîche', 'bananenflocken', 'hirsevollkornmehl', 'getrocknetes', 'zwiebel', 'potatoes', 'kohlensäurehaltiges', 
    'cream', 'cocoa', 'mass', 'bonbon', 'cyclamat', 'ruch', 'kichererbsenschrot', 'tablette', 'isländischmoosextrakt', 
    'eigwaren', 'pflaumen', 'karottensaft', 'lactobacilluskulturen', 'weissmais', 'presshefe','süssmais', 'natriumcarbonat', 'sunflower', 
    'ol', 'gelatinesäuerungsmittel', 'kakao', 'pâte', 'schnittkäse', 'hibiskusblüten', 'sesam', 'erbsenprotein', 'schnitzel', 'getreideflocken', 
    'glatt', 'weisses', 'weichweizenmehl', 'spring', 'tomatenpüree', 'kakaocrème', 'malzhaltig', 'weizenkörner',
    'sojalecithin', 'stärke', 'vollmilchpulver', 'dextrose', 'traubenzucker', 'kakaopulver', 'zitronensäure', 
    'hefeextrakt', 'weizenstärke', 'butterreinfett', 'säureregulator', 'palmfett', 'guarkernmehl', 'kräuter', 'palmöl', 
    'milchzucker', 'eigelb', 'nüsse', 'speisefettsäuren', 'geliermittel', 'vitamin', 'johannisbrotkernmehl', 'xanthan', 
    'feuchthaltemittel', 'petersilie', 'raps', 'pektin', 'diglyceride', 'lecithine', 'gerstenmalz', 'nitritpökelsalz', 
    'molkenpulver', 'milcheiweiss', 'gerste', 'vanilleextrakt', 'fette', 'vanillin', 'freilandhaltung', 'schalenfrüchte', 'peperoni', 
    'invertzuckersirup', 'streuwürze', 'mononatriumglutamat', 'weizenprotein', 'kokos', 'fettarmes', 'kulturen', 'milchsäure', 
    'basilikum', 'vanilleextrak', 'wachsmaisstärke', 'pflanzliches', 'kaliumsorbat', 'carrageen', 'natriumcarbonate', 'reisstärke', 'kokosfett', 
    'lauch', 'kohlensäure', 'betacarotin', 'sonnenblumenlecithin', 'vanille', 'schwarze', 'chili', 'vitamine', 'würze', 'paniermehl', 'acesulfam', 
    'sojalecithine', 'niacin', 'zimt', 'ingwer', 'mehlbehandlungsmittel', 'roggen', 'schwarzer', 'gummi', 'arabicum', 'zitrone', 'palmkern', 
    'kurkuma', 'weizenkleber', 'milchproteine', 'zwiebelpulver', 'natriumhydrogencarbonat', 'eiern', 'kokosöl', 'oregano', 'gerstenmalzmehl', 
    'sojamehl', 'paprikaextrakt', 'sauerteig', 'karotte', 'malzmehl', 'glycerin', 'würzmischung', 'folsäure', 'glucose', 'sonnenblume', 
    'aspartam', 'gewürzextrakt', 'gemahlen', 'knoblauchpulver', 'backhefe', 'rosmarin', 'koriander', 'zucchetti', 'pantothensäure', 
    'natriumcitrat', 'gewürz', 'weizenkeime', 'extrakt', 'senfsamen', 'alkohol', 'weizengluten', 'thymian', 'riboflavin', 
    'trennmittel', 'frucht', 'sorbitsirup', 'carnaubawachs', 'curry', 'eiweisspulver', 'sahne', 'molkenerzeugnis', 'gemüsebouillon', 
    'weisswein', 'öl', 'senfkörner', 'schwefeldioxid', 'gewürzzubereitung', 'ricotta', 'volleipulver', 'natriumnitrit', 'tapiokastärke', 
    'muskatnuss', 'milchsäurebakterien', 'haselnüssen', 'mehl', 'biotin', 'sucralose', 'hopfen', 'rohzucker', 'kreuzkümmel', 
    'sojasauce', 'ammoniumcarbonat', 'sonnenblumen', 'natriumascorbat', 'gelb', 'orange', 'fisch', 'laktose', 'natriummetabisulfit', 
    'cayennepfeffer', 'unjodiert', 'säureregulatoren', 'thiamin', 'süssmolkenpulver', 'geröstet', 'heidelbeeren', 
    'speisegelatine', 'fruchtzucker', 'eigelbpulver', 'leinsamen', 'nat', 'karamellisierter', 'fruktose', 'haselnuss', 
    'curcuma', 'pflanzenmargarine','sodium', 'caramelzuckersirup', 'röstkaffee', 'orangenschalen', 'nüssen', 
    'kaffee', 'tomatenpulver', 'getrockneter', 'bienenwachs', 'sesamsamen', 'zuckerkulör', 'rindfleischextrakt', 'weizenfasern', 
    'caramel', 'konzentrierter', 'hülle', 'hartschalenobst', 'eingesottene', 'caramelzucker', 'kartoffel', 'mineralstoffe', 
    'zitronenschalen', 'sulfite', 'acid', 'milchpulver', 'rotwein', 'ol', 'glutenfrei', 'melonen', 
    'raucharoma', 'fettarm', 'kurkumin', 'calciumcarbonat', 'natriumcitrate', 'shea', 'frischhefe', 'würfelzucker',
    'maniokstärke', 'pflanzenfettöl', 'rettich', 'kirsch', 'butterfett', 'traubenmost', 'schalenfrüchten', 'glukose', 
    'rosmarinextrakt', 'rapslecithin', 'zuckersirup', 'kaffeeextrakt', 'steinpilze', 'zitronen', 'randensaftkonzentrat', 
    'essigsäure', 'tapioca', 'kaliummetabisulfit', 'saflor', 'spirulina', 'rind', 'kaumasse', 'johannisbeeren', 
    'acerolapulver', 'magnesiumcarbonat', 'calciumchlorid', 'kiwi', 'peperoncino', 'erdbeere', 'carotten', 'zitronenaroma', 
    'quinoa', 'eb', 'phenylalaninquelle', 'weinsäure', 'schwarten', 'bananen', 'tomatenmarkkonzentrat', 'fructose', 
    'stärken', 'speiseessig', 'eipulver', 'milchbestandteile', 'teig', 'apfelsäure', 'rahmfrischkäse', 'kokosnussöl', 
    'pflanzenkonzentrate', 'invertase', 'kümmel', 'natriumglutamat', 'pflanzenfett', 'majoran', 'limettensaft', 'peperonis',
    'kondensierte', 'annatto', 'pfirsich', 'orangensaftkonzentrat', 'eisen', 'milchserum', 'pektine', 
    'rosinen', 'invertzucker', 'labart', 'fenchel', 'weizenquellmehl', 'lecithin', 'kardamom', 'rauch', 
    'himbeere', 'schweinegelatine', 'koffein', 'pfefferminze', 'füllung', 'pflanzenöl', 'rum', 'rosenkohl', 'echalotten',
    'walnusskerne',  'leinsaat', 'grappa', 'orangenaroma', 'vanillesamen', 'brauner', 'ananassaft', 'bienenhonig',
    'zuckerarten', 'verzehr', 'bouillon', 'melasse', 'nahrungsfasern', 'paprikapulver', 'natriumalginat', 'zitronenverbene',
    'vanilleschoten', 'cognac', 'dinatriuminosinat', 'fruchtpüree', 'konzentrate', 'molkepulver', 'margarine', 'radieschen',
    'konzentrierte', 'schmelzsalze', 'diglyceriden', 'dill', 'knospe', 'sojaöl', 'blumenkohl', 'hopfenextrakt', 
    'zinksulfat', 'wein', 'karmin', 'pastinaken', 'essiggurken', 'zitrusfasern', 'mascarpone', 'fingerauberginen',
    'karamellzuckersirup', 'gemahlener', 'auberginen', 'vegetabil', 'vit', 'pinienkerne', 'pininenkerne', 'grüner', 'grapefruit',
    'natriumhydroxid', 'gemüsekonzentrate', 'frischeiern', 'weizenmalzmehl', 'trehalose', 'gemüsepaprika', 'mandarinen',
    'zitronensaftpulver', 'sahnepulver', 'dinatriumguanylat', 'vergine', 'schinken', 'rucola', 'carotine', 'grapefruitsaft',
    'nelken', 'roter', 'zitronengras', 'calciumcitrat', 'meerrettich', 'äpfelsäure', 'maltitsirup', 'hirse', 'brennesseln',
    'buttermilchpulver', 'rahmweichkäse', 'apfelstücke', 'kokosflocken', 'geräuchert', 'glukosequelle', 'eiklar', 'lindenblüten',
    'whisky', 'kandierte', 'bananenpüree', 'papaya', 'stark', 'früchten', 'holunder', 'sesamöl', 'haselnusskerne',
    'blanch', 'birnensaft', 'mangopüree', 'hühnereieiweisspulver', 'pflanzenöle', 'zuckerhut', 'salt', 'feinkristallzucker',
    'lorbeerblätter', 'alcohol', 'traube', 'baumnuss', 'pulver', 'dextrin', 'karottensaftkonzentrat', 'pilze', 'erdnuesse',
    'zitruspektin', 'schokoladenpulver', 'karamellzucker', 'maltit', 'hartweizen', 'dunkel', 'saft', 'blutorangensaft',
    'weizenmalz', 'liebstöckel', 'zuck', 'gesamtmilchbestandteile', 'kaliumchlorid', 'schmelzkäse', 'couverture', 
    'salbei', 'kirsche', 'holundersaftkonzentrat', 'gewürzmischung', 'panade', 'buchweizen', 'palmkernöl', 'aceto',
    'mikrobiell', 'kaliumjodid', 'banane', 'fruktosesirup', 'bourbon', 'kaliumnitrat', 'speisewürze', 'randensaft', 
    'säurungsmittel', 'wildfang', 'methylcellulose', 'sirup', 'eisberg', 'passionsfrucht', 'fruchtsaftkonzentrat', 
    'enzyme', 'lollo', 'gefriergetrocknet', 'steviolglycoside', 'freilandauslaufhaltungp', 'kaliumjodat', 'salanova', 
    'corn', 'rosso', 'judasohren', 'vegan', 'tomate', 'aqua', 'sojalezithin', 'weinbrand', 'brombeerblätter', 
    'zitronenöl', 'taurin', 'saccharose', 'pecannüsse', 'ethanol', 'chilipulver', 'rinde', 'titandioxid', 'apfelpektin', 
    'milchfermente', 'gräten', 'mageres', 'vanillezucker', 'parmigiano', 'dicalciumphosphat', 'holunderbeere', 'meersalz',
    'calciumphosphat', 'reggiano', 'calciumphosphate', 'lorbeer', 'gelbe', 'estragon', 'sonnenblumenlecithine', 'safran',
    'weizengriess', 'tee', 'magnesium', 'milchanteil', 'zitronenkonzentrat', 'heidelbeere', 'passionsfruchtsaft', 
    'spirulinakonzentrat', 'kaliumiodid', 'erdnüssen', 'käsereikulturen', 'weizenkleie', 'flour', 'thunfisch', 'morcheln',
    'brühe', 'lactobacillus','aprikose', 'mikrobielles', 'karamellsirup', 'schafmilch', 'tafelessig', 'kokoswasser',
    'schmelzsalz', 'schellack', 'anthocyane', 'apfelpüree', 'milchproteinpulver', 'polyphosphate', 'chinakohl', 'mandelkerne',
    'glycol', 'molkeneiweisskäse', 'hydrolysiertes', 'tuber', 'vodka', 'kabis', 'erdbeerpüree', 'bockshornklee', 'avocados',
    'gerstenflocken', 'puderzucker', 'pflanzenfette', 'cellulose', 'aronia', 'kultur', 'zitronenschale', 'haselnusspaste', 
    'kräuterextrakt', 'tierisch', 'kräutermischung', 'grana', 'kakaokerne', 'gemahlene', 'holunderbeeren', 'padano', 
    'hühnereiweisspulver', 'natriumselenit', 'bärlauch', 'nüsslisalat', 'frühlingszwiebeln', 'lattich', 'cherrytomaten', 
    'schwarzteeextrakt', 'weizenvollkornschrot', 'kuhmilch', 'rohmilch', 'magermilch', 'bergmilch', 'buffelmilch', 'spargel',
    'milk', 'erdnusskerne', 'maronen', 'biovollmilch','ahornsirup', 'baumnüsse', 'baumnusskerne', 'edelkastanien', 'balsamicoessig',
    'nektarinen', 'lachsfilets',  'schweinkoteletten','schweinskoteletten', 'erdnussöl', 'kälbermagenlab', 'vollmilch', 'limonade', 'biorahm', 
    'biomilch','albacore', 'arabica', 'habaneros', 'thunus', 'levomentholum', 'pandalus', 'penaeus', 'pangasianodon', 
    'rosenmelisse', 'vollkornweizenflocken', 'peanuts', 'leine', 'ketchup', 'zuckerrohr', 'urdinkelvollkornschrot', 'blattspinat', 
    'rotkraut', 'zitronenmelisse', 'orangenminze', 'hagebutte', 'goldmelisse', 'popcorn', 'lachsforelle', 'schafsmilch', 'brokkoli',
    'pangasius', 'bachforelle', 'trutta', 'fario', 'maisgrieß', 'urdinkelruchmehl', 'vollkorngerstenflocken', 'bier', 'macadamianüsse', 
    'langkirnreis', 'macadamianusskerne', 'vollfetthartkäse', 'dornbusch', 'quor', 'tuna', 'thun', 'reisvollkornmehl', 'kartoffelpüreepulver', 
    'pastmilch', 'soeisequark', 'cabernet', 'sauvignon', 'lammfleisch', 'kaltwassercrevetten', 'kapernäpfel', 'dosidicus', 'gigas', 
    'miesmuschelfleisch', 'mytilus', 'chilensis', 'pangasiusfilet', 'gorgonzola', 'chilipaste', 'chilis', 'minze', 'hibiscus', 'backtreibmittel',
    'holunderblüten', 'spitzwegerichblätter', 'krauseminze', 'hagebuttenschalen', 'silberlindenblüten', 'lavendelblüten', 'cashew', 
    'vollkornaferflocken', 'zuckermais', 'pfifferlinge', 'kräuterseitlinge', 'kräuterseitling', 'vollrahm', 'blutenhonig', 'hühnereier', 'traubenkernöl', 'traubernkernöl', 'vollreis',
    'maiskolben', 'kamille', 'olivenöle', 'olivenölen', 'kastanien', 'straussenfleisch', 'kresse', 'weissweinessig', 'branntweinessig', 'magerjogurt',
    'kidneybohnen', 'kaffeebohnen', 'glucosesirup', 'rotweinessig', 'hypophthalmus', 'ringens', 'sojadrink', 'kohl', 'kokosnussmilch', 'doppelrahm',
    'glukosefruktosesirup', 'malzessig', 'gerstenmalzessig', 'glucosefructosesirup', 'zitronenthymian', 'mungobohnenstärke', 'saccharomyces', 'cerevisiae',
    'vollmiclh', 'cashews', 'cashewnuesse', 'rinderbouillon', 'spitzwegerichkraut', 'eglantier', 'artischocken', 'vollmiilch', 'oil', 'cacao',
]

# ---------- Grouping dictionary ----------------

grouped_words ={
    'ananas': ['aas'],
    'artischocken': ['artischockenherzen'],
    'alkohol': ['alcohol'],
    'aprikose': ['aprikosen'],
    'avocado': ['avocados'],
    'auberginen': ['fingerauberginen'],
    'broccoli': ['brokkoli'], 
    'balsamico': ['balsamicoessig'],
    'banane': ['bananen'],
    'baumnuss': ['baumnusskerne', 'baumnüsse',],
    'bohnen': ['borlottibohnen'],
    'büffelmilch': ['buffelmilch'],
    'mais': ['weissmais'],
    'caramel': ['karamell'],
    'calciumphosphat': ['calciumphosphate'],
    'carotin': ['carotine'],
    'cashew': ['cashewkerne', 'cashewnuesse', 'cashewnüsse', 'cashews'],
    'chiasamen': ['chia'],
    'dorsch': ['dorschfilets'],
    'eier': ['hühnereier', 'bioeier', 'eiern', 'frischeiern'],
    'eierspätzle': ['eierspätzli'],
    'endivien': ['endiviensalat', 'endivie'],
    'erdnuss': ['erdnuesse', 'erdnusskerne'],
    'eisberg': ['eisbergsalat'],
    'erdbeere': ['erdbeeren'],
    'erdnuesse': ['erdnuss', 'erdnusskerne', 'erdnüsse', 'erdnüssen'],
    'fettarm': ['fettarmer', 'fettarmes'],
    'fruktoseglukosesirup': ['fructoseglucosesirup', 'glukosefruktosesirup', 'glucosefructosesirup' ],
    'feta': ['biofeta'],
    'fructose': ['fruktose'],
    'früchte': ['früchten'],
    'geröstet': ['geröstete'],
    'getrocknet': ['getrocknete', 'getrockneter', 'getrocknetes'],
    'gezuckert': ['gezuckerte'],
    'gurken': ['gurke'],
    'hagebutte': ['hagebutten'],
    'hartweizengriess': ['hartweizengrieß'], 
    'haselnuss': ['haselnusskerne', 'haselnüsse', 'haselnüssen'],
    'heidelbeere': ['heidelbeeren'],
    'hibiscus': ['hibiskus'],
    'himbeere': ['himbeeren'],
    'hefe': ['presshefe', 'frischhefe'],
    'holunderbeere': ['holunderbeeren'],
    'honig': ['blutenhonig', 'blütenhonig', 'bienenhonig'],
    'joghurt': ['jogutr', 'vollmilchjoghurt', 'vollmilchjogurt', 'magerjoghurt'],
    'johannisbeere': ['johannisbeeren'],
    'käse': ['kaese'],
    'marroni': ['edelkastanien', 'maronen', 'kastanien'],
    'mandeln': ['mandelkerne'],
    'milch': ['kuhmilch','rohmilch', 'vollmilch', 'biovollmilch', 'biomilch'
             'magermilch', 'ziegenmilch', 'bergmilch', 'milk', 'vollmiclh', 'vollmiilch'],
    'karotten': ['carotten'],
    'kiwi': ['kiwis'],
    'kokosmilch': ['kokosnussmilch'],
    'kokoswasser': ['kokosnusswasser'],
    'kokosfett': ['kokosnussfett'],
    'kokosraspel': ['kokosraspeln'],
    'kräuterseitlinge': ['kräuterseitling'],
    'kurkuma': ['curcuma'],
    'lactose': ['laktose'],
    'langkornreis': ['langkirnreis'],
    'lecithin': ['lecithine'],
    'macadamianusskerne': ['macadamianüsse'],
    'maisgriess': ['maisgrieß'],
    'melone': ['melonen'],
    'milcheiweiss': ['milcheiweiß'],
    'milchprotein': ['milchproteine'],
    'molkenpulver': ['molkepulver'],

    'olivenöl': ['olivenöle', 'olivenölen'],
    'orangensaft': ['blutorangensaft'],
    'öl': ['oil'],

    'vollkornhaferflocken': ['hafervollkornflocken'],
    'weizenvollkornmehl': ['vollkornweizenmehl'],


    'schafmilch': ['schafsmilch'],
    'rahm': ['vollrahm', 'biorahm'],
    'reis': ['vollreis'], 

    'wasser': ['wass'],
    'traubenkernöl': ['traubernkernöl'],
    'zucker': ['feinkristallzucker', 'zuck', 'würfelzucker'],
    'zucchetti': ['zucchini'],
    'zuckermais': ['süssmais'],
    'pinienkerne': ['pininenkerne'],
    'salz': ['meersalz'],
    'pfefferminz': ['pfefferminzblätter'],
    'spargeln': ['spargelspitzen', 'spargel'],
    'peperoni': ['peperonis'],
    'schweinkoteletten': ['schweinskoteletten'],

}